pub const SEPOLIA_MAX_BLOCK_TIME: u64 = 30;
pub const MAINNET_MAX_BLOCK_TIME: u64 = 30;

pub const SEPOLIA_MAX_NUM_OF_EVENTS_PER_TRANSACTION: u64 = 30;
pub const MAINNET_MAX_NUM_OF_EVENTS_PER_TRANSACTION: u64 = 30;
