[package]
name = "conode-logging"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { workspace = true }
chrono = { version = "0.4.38", features = ["serde"] }
once_cell = "1.20.2"
